<?xml version="1.0" encoding="utf-8"?>
<log>
<entry code="info" level="info">
 <message>[info] Activation of plug-in DQC Rules Validator successful, version Check version using Tools->DQC->Version on the GUI or --dqc-version on the command line. - validate/DQC </message>
 <ref href="validate/DQC"/></entry>
<entry code="info" level="info">
 <message>[info] Activation of plug-in SEC Inline Transforms successful, version 19.2. - transforms/SEC </message>
 <ref href="transforms/SEC"/></entry>
<entry code="info" level="info">
 <message>[info] Xule version: 3.0.23694 - </message>
 <ref href=""/></entry>
<entry code="info" level="info">
 <message>[info] loaded in 7.24 secs at 2024-02-12T11:07:49 - http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm </message>
 <ref href="http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm"/></entry>
<entry code="exception:FileNotFoundError" level="error">
 <message instance="plt-20210403.htm" error="[Errno 2] No such file or directory: 'D:/DJT/Documents/GitHub/davidtauriello/dqc_us_rules/dqc_us_rules/dqc-us-2020-V22-ruleset.z...">[exception:FileNotFoundError] Instance validation exception: [Errno 2] No such file or directory: 'D:/DJT/Documents/GitHub/davidtauriello/dqc_us_rules/dqc_us_rules/dqc-us-2020-V22-ruleset.zip', instance: plt-20210403.htm - http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm 
Traceback (most recent call last):
  File &quot;D:\a\Arelle\Arelle\arelle\Validate.py&quot;, line 109, in validate
  File &quot;D:\a\Arelle\Arelle\arelle\ValidateXbrl.py&quot;, line 565, in validate
  File &quot;C:\Program Files\Arelle\plugin\xule\__init__.py&quot;, line 1009, in xuleValidate
    runXule(_cntlr, options, val.modelXbrl, xule_validator['map_name'])
  File &quot;C:\Program Files\Arelle\plugin\xule\__init__.py&quot;, line 918, in runXule
    rule_set.open(rule_set_location, open_packages=not getattr(options, 'xule_bypass_packages', False))
  File &quot;C:\Program Files\Arelle\plugin\xule\XuleRuleSet.py&quot;, line 120, in open
    file_object = self._get_rule_set_file_object()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;C:\Program Files\Arelle\plugin\xule\XuleRuleSet.py&quot;, line 159, in _get_rule_set_file_object
    file_object = file_source.file(self.location, binary=True)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;D:\a\Arelle\Arelle\arelle\FileSource.py&quot;, line 591, in file
  File &quot;D:\a\Arelle\Arelle\arelle\FileSource.py&quot;, line 790, in openFileStream
FileNotFoundError: [Errno 2] No such file or directory: 'D:/DJT/Documents/GitHub/davidtauriello/dqc_us_rules/dqc_us_rules/dqc-us-2020-V22-ruleset.zip'</message>
 <ref href="http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm"/></entry>
<entry code="info" level="info">
 <message>[info] validated in 1.29 secs - http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm </message>
 <ref href="http://www.sec.gov/Archives/edgar/data/914025/000091402521000019/plt-20210403.htm"/></entry>
</log>
